[project]
name = "cv-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datetime>=5.5",
    "dotenv>=0.9.9",
    "gradio>=5.39.0",
    "openai-agents>=0.2.4",
    "pypdf>=5.9.0",
    "requests>=2.32.4",
]
